<head xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <title>Калькулятор</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <!--    <link rel="stylesheet" type="text/css" href="/css/style.css" />-->
    <script
            src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous">
        </script>
</head>
<form method="POST" action="/src/code/App/Controller/CalcController.php">
<div class="deck_box">
    <h1> калькулятор</h1>
    <div>
        самый просто калькулятор
    </div>
    <div>
        <input type="text" name="calc" id="idCalc" autocomplete="off"></br>
        <input type="submit" name="Равно" id="idGo" value="Равно" onclick="return false"></br>
        <input type="text" name="result" id="idRes" autocomplete="off" placeholder="Ответ">
        <script type="text/javascript">
            $('#idGo').on('click',function(){
                var newStr = document.getElementById('idCalc').value;
                $.ajax({
                    type: 'POST',
                    url: '/App/Controller/CalcController.php',
                    data: {postStr: newStr},
                    success: function (response) {
                        var jsonData = JSON.parse(response);
                        document.getElementById('idRes').value = jsonData.success;
                    }

                });
            });





        </script>

    </div>

</div>
</form>