<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="/css/style.css" />
    <title>Колода</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

</head>
<body>
<br>
<h1> Колода карт</h1>

<br>

    <div class="deck_box">

        <div>
            здесь будет список карт
        </div>



    </div>
<br>
    <p>
        123

    </p>
<br>
    <a href="/App/View/Main.phtml">Главная страница</a> </br>
</body>


