<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--    <link rel="stylesheet" type="text/css" href="/css/style.css" />-->
    <title>Главная</title>
    <link rel="stylesheet" type="text/css" href="/css/style.css" />
</head>
<body>
<br>
<h1>Добро пожаловать!</h1>
<br>
<!--    <img src="/src/code/App/Image/Sword.jpg" align="left" >-->
   Главная страница, при отправке main, или по умолчанию открывается она
<br>
    <a href="/App/View/Main.phtml">Главная страница</a> </br>
    <a href="/App/View/Calc.phtml">Калькулятор</a> </br>
    <a href="/App/View/Sword.phtml">Первый игрок</a></br>
    <a href="/App/View/Def.phtml">Второй игрок</a></br>
    <a href="/App/View/Deck.phtml">Калода карт</a> </br>
<p>
строка
</p>
</body>